language: java
jdk: oraclejdk7

install:
- ./gradlew install
script:
- ./gradlew check
- GRADLE_VERSION=2.2.1 ./acceptance-test/run-test.sh
- GRADLE_VERSION=1.12  ./acceptance-test/run-test.sh

after_success:
- test ${TRAVIS_TAG} && ./gradlew -Pversion=${TRAVIS_TAG#v} bintrayUpload

env:
  global:
  - TERM=dumb
  - secure: O1woxzaGDbP7FjbnfCryVwfjOqqTU8Ix7dieAdOSwdfLS21RxV5vBdk7rgep+Gpgj0bhMILHpnlmuH6oh5oLNykQL2DKhC4atjyWjTZBVKMBvDabPDKXrsT8pvexYzwTUlMACcEU8/iBvNjqJjkJzQy1TuIrknqXp4GdTzlyyko=
  - secure: hUWvSso9YoE9v1FDiJUzsURae4dpNFK5J59UqeKqyD17Mz4tefZtTzMcsbx9qe+6Y7VT6RsH/MAryosJz53OzDQQX0NBWWNsCpxNU97/cSbmw2Tl3523pKc5irjbv43+vFF5kSya16AmRcAAymbAzpNnvKDFujXONRYbnhYRYV8=
